model_bucket = "***REMOVED***s"
lambda_function_local_path = "../web_service/lambda_function.py"
docker_image_local_path = "../web_service/Dockerfile"
ecr_repo_name = "prod-fake-news-detect"
lambda_function_name = "prod-classify-lambda"
region = "us-east-1"
