model_bucket = "***REMOVED***s"
lambda_function_local_path = "../web-service/lambda_function.py"
docker_image_local_path = "../web-service/Dockerfile"
ecr_repo_name = "prod-fake-news-detect"
lambda_function_name = "prod-classify-lambda"
