#!/usr/bin/env bash

export KAGGLE_USERNAME="***REMOVED***"
export KAGGLE_KEY="***REMOVED***"
export DATA_PATH="***REMOVED***"
export ARTIFACT_LOC="***REMOVED***"
export MLFLOW_TRACKING_URI="***REMOVED***"
export MLFLOW_TRACKING_USERNAME="***REMOVED***"
export MLFLOW_TRACKING_PASSWORD="***REMOVED***"
export AWS_SECRET_ACCESS_KEY="***REMOVED***"
export AWS_ACCESS_KEY_ID="***REMOVED***"
export AWS_DEFAULT_REGION="us-east-1"

touch .env
echo "KAGGLE_USERNAME = $KAGGLE_USERNAME" > .env
echo "KAGGLE_KEY = $KAGGLE_KEY" >> .env
echo "DATA_PATH = $DATA_PATH" >> .env
echo "MLFLOW_TRACKING_URI = $MLFLOW_TRACKING_URI" >> .env
echo "MLFLOW_TRACKING_USERNAME = $MLFLOW_TRACKING_USERNAME" >> .env
echo "MLFLOW_TRACKING_PASSWORD = $MLFLOW_TRACKING_PASSWORD" >> .env
echo "AWS_SECRET_ACCESS_KEY = $AWS_SECRET_ACCESS_KEY" >> .env
echo "AWS_ACCESS_KEY_ID = $AWS_ACCESS_KEY_ID" >> .env
echo "AWS_DEFAULT_REGION = $AWS_DEFAULT_REGION" >> .env
