#!/usr/bin/env bash

export KAGGLE_USERNAME=""
export KAGGLE_KEY=""
export DATA_PATH=""
export MODEL_BUCKET=""
export PROJECT_ID=""
export ARTIFACT_LOC="s3://${MODEL_BUCKET}-${PROJECT_ID}"
export MLFLOW_TRACKING_URI=""
export TFSTATE_BUCKET=""
export MLFLOW_TRACKING_USERNAME=""
export MLFLOW_TRACKING_PASSWORD=""
export AWS_SECRET_ACCESS_KEY=""
export AWS_ACCESS_KEY_ID=""
export AWS_DEFAULT_REGION=""
export ECR_REPO=""
export MODEL_NAME=""
export ECR_REPO_NAME="${ECR_REPO}-${PROJECT_ID}"
touch .env
echo "KAGGLE_USERNAME = $KAGGLE_USERNAME" > .env
echo "KAGGLE_KEY = $KAGGLE_KEY" >> .env
echo "DATA_PATH = $DATA_PATH" >> .env
echo "MLFLOW_TRACKING_URI = $MLFLOW_TRACKING_URI" >> .env
echo "MLFLOW_TRACKING_USERNAME = $MLFLOW_TRACKING_USERNAME" >> .env
echo "MLFLOW_TRACKING_PASSWORD = $MLFLOW_TRACKING_PASSWORD" >> .env
echo "AWS_SECRET_ACCESS_KEY = $AWS_SECRET_ACCESS_KEY" >> .env
echo "AWS_ACCESS_KEY_ID = $AWS_ACCESS_KEY_ID" >> .env
echo "AWS_DEFAULT_REGION = $AWS_DEFAULT_REGION" >> .env
echo "ARTIFACT_LOC = $ARTIFACT_LOC" >> .env
echo "ECR_REPO_NAME = $ECR_REPO_NAME" >> .env
echo "MODEL_NAME = $MODEL_NAME" >> .env
echo "TFSTATE_BUCKET = $TFSTATE_BUCKET" >> .env
echo "MODEL_BUCKET = $MODEL_BUCKET" >> .env
echo "PROJECT_ID = $PROJECT_ID" >> .env
