{
 "title": "Evidently Classification Performance Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "metric",
    "query": {
     "query": "label_values(evidently:classification_performance:quality, metric)"
    }
   },
   {
    "name": "classes",
    "query": {
     "query": "label_values(evidently:classification_performance:class_confusion, class_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Reference dataset data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Quality",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "evidently:classification_performance:quality{dataset=\"current\"}",
     "legendFormat": "{{metric}}"
    }
   ]
  },
  {
   "title": "$metric",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
   "repeat": "metric",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "evidently:classification_performance:quality{dataset=\"current\", metric=\"$metric\"}"
    }
   ]
  },
  {
   "title": "Prediction class representation",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "evidently:classification_performance:class_representation{dataset=\"current\", type=\"prediction\"}",
     "legendFormat": "{{class_name}}"
    }
   ]
  },
  {
   "title": "Target class representation",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "evidently:classification_performance:class_representation{dataset=\"current\", type=\"target\"}",
     "legendFormat": "{{class_name}}"
    }
   ]
  },
  { "title": "Class $classes information ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 }, "repeat": "classes" },
  {
   "title": "Confusion $classes",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "evidently:classification_performance:class_confusion{dataset=\"current\", class_name=\"${classes:raw}\"}",
     "legendFormat": "{{metric}}"
    }
   ]
  },
  {
   "title": "Confusion in time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 5, "y": 29 },
   "targets": [
    {
     "expr": "evidently:classification_performance:class_confusion{dataset=\"current\", class_name=\"${classes:raw}\"}",
     "legendFormat": "{{metric}}"
    }
   ]
  },
  {
   "title": "Quality",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 29 },
   "targets": [
    {
     "expr": "evidently:classification_performance:class_quality{dataset=\"current\", class_name=\"${classes:raw}\"}",
     "legendFormat": "{{metric}}"
    }
   ]
  }
 ]
}